DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  passwd TEXT NOT NULL
);

CREATE TABLE auta (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  car_name TEXT UNIQUE NOT NULL,
  engine TEXT NOT NULL,
  fuel TEXT NOT NULL,
  gearbox TEXT NOT NULL,
  seats INTEGER NOT NULL,
  car_image TEXT NOT NULL
);